-- =========================================================
-- SMART TROLLEY DATABASE SCHEMA
-- PostgreSQL 16
-- =========================================================

-- =========================================================
-- 1. USERS
-- Stores customers and administrators
-- =========================================================

CREATE TABLE users (
    user_id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(15) UNIQUE NOT NULL,
    address TEXT,
    role VARCHAR(20) NOT NULL DEFAULT 'customer'
        CHECK (role IN ('customer', 'admin')),
    registration_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    purchase_count INTEGER NOT NULL DEFAULT 0
        CHECK (purchase_count >= 0),
    account_status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (account_status IN ('active', 'inactive', 'blocked'))
);


-- =========================================================
-- 2. BASKETS
-- Stores physical Smart Trolley information
-- =========================================================

CREATE TABLE baskets (
    basket_id BIGSERIAL PRIMARY KEY,
    basket_number VARCHAR(50) UNIQUE NOT NULL,
    current_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,

    battery_status NUMERIC(5,2)
        CHECK (battery_status >= 0 AND battery_status <= 100),

    current_weight NUMERIC(10,3) NOT NULL DEFAULT 0
        CHECK (current_weight >= 0),

    connection_status VARCHAR(20) NOT NULL DEFAULT 'offline'
        CHECK (connection_status IN ('online', 'offline', 'error')),

    current_location VARCHAR(150),

    basket_status VARCHAR(20) NOT NULL DEFAULT 'available'
        CHECK (basket_status IN ('available', 'in_use', 'maintenance', 'offline')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 3. BASKET MODULES
-- Stores Raspberry Pi, ESP32, camera, sensors, servos, etc.
-- =========================================================

CREATE TABLE basket_modules (
    module_id BIGSERIAL PRIMARY KEY,
    basket_id BIGINT NOT NULL
        REFERENCES baskets(basket_id) ON DELETE CASCADE,

    module_type VARCHAR(50) NOT NULL,

    module_identifier VARCHAR(100),

    connection_status VARCHAR(20) NOT NULL DEFAULT 'offline'
        CHECK (connection_status IN ('online', 'offline', 'error')),

    module_status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (module_status IN ('active', 'inactive', 'fault')),

    current_value NUMERIC(12,3),

    unit VARCHAR(30),

    last_seen TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 4. SESSIONS
-- Handles login, OTP verification and automatic logout
-- OTP itself is NOT stored in plain text
-- =========================================================

CREATE TABLE sessions (
    session_id BIGSERIAL PRIMARY KEY,

    user_id BIGINT NOT NULL
        REFERENCES users(user_id) ON DELETE CASCADE,

    otp_hash TEXT,

    otp_verified BOOLEAN NOT NULL DEFAULT FALSE,

    otp_expires_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    expires_at TIMESTAMPTZ,

    verified_at TIMESTAMPTZ,

    logged_out_at TIMESTAMPTZ
);


-- =========================================================
-- 5. PRODUCTS
-- Stores supermarket product catalogue
-- =========================================================

CREATE TABLE products (
    product_id BIGSERIAL PRIMARY KEY,

    barcode VARCHAR(100) UNIQUE NOT NULL,

    product_name VARCHAR(200) NOT NULL,

    category VARCHAR(100),

    price NUMERIC(10,2) NOT NULL
        CHECK (price >= 0),

    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0
        CHECK (discount_percent >= 0 AND discount_percent <= 100),

    gst_percent NUMERIC(5,2) NOT NULL DEFAULT 0
        CHECK (gst_percent >= 0 AND gst_percent <= 100),

    weight NUMERIC(10,3) NOT NULL
        CHECK (weight > 0),

    stock_quantity INTEGER NOT NULL DEFAULT 0
        CHECK (stock_quantity >= 0),

    image_url TEXT,

    description TEXT,

    manufacture_date DATE,

    expiry_date DATE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (
        expiry_date IS NULL
        OR manufacture_date IS NULL
        OR expiry_date >= manufacture_date
    )
);


-- =========================================================
-- 6. CART ITEMS
-- Stores the customer's currently active cart
-- cart_id is a logical cart identifier generated by backend
-- =========================================================

CREATE TABLE cart_items (
    cart_item_id BIGSERIAL PRIMARY KEY,

    cart_id UUID NOT NULL,

    user_id BIGINT NOT NULL
        REFERENCES users(user_id) ON DELETE CASCADE,

    basket_id BIGINT NOT NULL
        REFERENCES baskets(basket_id) ON DELETE CASCADE,

    product_id BIGINT NOT NULL
        REFERENCES products(product_id) ON DELETE RESTRICT,

    product_name VARCHAR(200) NOT NULL,

    quantity INTEGER NOT NULL DEFAULT 1
        CHECK (quantity > 0),

    unit_price NUMERIC(10,2) NOT NULL
        CHECK (unit_price >= 0),

    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0
        CHECK (discount_percent >= 0 AND discount_percent <= 100),

    weight NUMERIC(10,3) NOT NULL DEFAULT 0
        CHECK (weight >= 0)
);


-- =========================================================
-- 7. TRANSACTIONS
-- Stores completed bills and payment information
-- items JSONB preserves the final bill's product details
-- =========================================================

CREATE TABLE transactions (
    transaction_id BIGSERIAL PRIMARY KEY,

    user_id BIGINT NOT NULL
        REFERENCES users(user_id) ON DELETE RESTRICT,

    basket_id BIGINT NOT NULL
        REFERENCES baskets(basket_id) ON DELETE RESTRICT,

    cart_id UUID,

    items JSONB NOT NULL DEFAULT '[]'::jsonb,

    total_amount NUMERIC(12,2) NOT NULL
        CHECK (total_amount >= 0),

    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0
        CHECK (discount_amount >= 0),

    gst_amount NUMERIC(12,2) NOT NULL DEFAULT 0
        CHECK (gst_amount >= 0),

    final_amount NUMERIC(12,2) NOT NULL
        CHECK (final_amount >= 0),

    payment_method VARCHAR(30) NOT NULL DEFAULT 'UPI'
        CHECK (payment_method IN ('UPI')),

    payment_status VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (payment_status IN ('pending', 'successful', 'failed', 'cancelled')),

    payment_reference VARCHAR(200),

    transaction_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 8. EVENTS LOG
-- Security, hardware and system activity
-- =========================================================

CREATE TABLE events_log (
    event_id BIGSERIAL PRIMARY KEY,

    user_id BIGINT
        REFERENCES users(user_id) ON DELETE SET NULL,

    basket_id BIGINT
        REFERENCES baskets(basket_id) ON DELETE SET NULL,

    event_type VARCHAR(50) NOT NULL,

    event_description TEXT NOT NULL,

    metadata JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- INDEXES
-- Improve commonly used searches
-- =========================================================

CREATE INDEX idx_users_phone
    ON users(phone_number);

CREATE INDEX idx_baskets_current_user
    ON baskets(current_user_id);

CREATE INDEX idx_basket_modules_basket
    ON basket_modules(basket_id);

CREATE INDEX idx_sessions_user
    ON sessions(user_id);

CREATE INDEX idx_products_barcode
    ON products(barcode);

CREATE INDEX idx_products_category
    ON products(category);

CREATE INDEX idx_cart_items_cart
    ON cart_items(cart_id);

CREATE INDEX idx_cart_items_user
    ON cart_items(user_id);

CREATE INDEX idx_transactions_user
    ON transactions(user_id);

CREATE INDEX idx_transactions_date
    ON transactions(transaction_date);

CREATE INDEX idx_events_basket
    ON events_log(basket_id);

CREATE INDEX idx_events_created
    ON events_log(created_at);